---
/content/documents/corporate-website/services:
  .meta:order-before: data-and-information
  /content:
    /content[1]:
      /website:additionalinformation:
        hippostd:content: ''
        jcr:primaryType: hippostd:html
      /website:icon:
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
        jcr:primaryType: hippogallerypicker:imagelink
      /website:image:
        hippo:docbase: 4d3252da-3269-4acf-9641-2fae51b123dc
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
        jcr:primaryType: hippogallerypicker:imagelink
      /website:introduction:
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
        jcr:primaryType: hippostd:html
      /website:primarysections[1]:
        /website:primarysectionlinks:
          /website:icon:
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
            jcr:primaryType: hippogallerypicker:imagelink
          /website:link:
            hippo:docbase: dfcabd86-263b-4612-85b1-4d8c1be48530
            jcr:primaryType: hippo:mirror
          jcr:primaryType: website:visualinternallink
          website:shortsummary: ''
        /website:tilesectionvisualhub[1]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Our free&nbsp;GCHQ-certified board-level training
              will help you to understand how cyber security risks could affect your
              organisation.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: GCHQ-certified board training
        /website:tilesectionvisualhub[2]:
          /website:tilesectionintroduction:
            hippostd:content: <p>We offer free onsite assessments to help your NHS
              organisation identify vulnerabilities and understand and overcome areas
              of high risk.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Onsite assessments
        /website:tilesectionvisualhub[3]:
          /website:tilesectionintroduction:
            hippostd:content: <p>To help your NHS organisation prepare for onsite
              cyber security reassessment, we offer free support to address cyber-critical
              issues that can have clinical impact and threaten patient safety.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Cyber operational readiness
        /website:tilesectionvisualhub[4]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Our free technical remediation service offers support
              to NHS Organisations to help fix technical issues in existing technology
              and systems to help achieve the Cyber Essential Plus accreditation.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical remediation
        jcr:primaryType: website:primarysectionvisualhub
        website:primarysectionheading: Incident management
      /website:primarysections[2]:
        /website:primarysectionlinks:
          /website:icon:
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
            jcr:primaryType: hippogallerypicker:imagelink
          /website:link:
            hippo:docbase: 4b6056e1-221a-4d3d-81dd-65a628e1efa1
            jcr:primaryType: hippo:mirror
          jcr:primaryType: website:visualinternallink
          website:shortsummary: ''
        /website:tilesectionvisualhub[1]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Technical Support Tile 1 introduction</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical Support Tile 1
        /website:tilesectionvisualhub[2]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Technical Support Tile 2 introduction</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical Support Tile 2
        jcr:primaryType: website:primarysectionvisualhub
        website:primarysectionheading: Technical Support
      /website:seosummary:
        hippostd:content: We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.
        jcr:primaryType: hippostd:html
      /website:summary:
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
        jcr:primaryType: hippostd:html
      common:searchRank: 3
      common:searchable: true
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2020-03-30T15:55:31.360Z
      hippostdpubwf:lastModificationDate: 2020-03-30T17:05:04.762Z
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 34470706-6ff2-458d-84e8-7c418f469f98
      hippotranslation:locale: en
      jcr:mixinTypes:
      - mix:referenceable
      jcr:primaryType: website:visualhub
      website:shortsummary: Our information, data, and IT systems help health professionals,
        commissioners, analysts and managers give the best outcomes for patients.
      website:title: Services and resources
    /content[2]:
      /website:additionalinformation:
        hippostd:content: ''
        jcr:primaryType: hippostd:html
      /website:icon:
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
        jcr:primaryType: hippogallerypicker:imagelink
      /website:image:
        hippo:docbase: 4d3252da-3269-4acf-9641-2fae51b123dc
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
        jcr:primaryType: hippogallerypicker:imagelink
      /website:introduction:
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
        jcr:primaryType: hippostd:html
      /website:primarysections[1]:
        /website:primarysectionlinks:
          /website:icon:
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
            jcr:primaryType: hippogallerypicker:imagelink
          /website:link:
            hippo:docbase: dfcabd86-263b-4612-85b1-4d8c1be48530
            jcr:primaryType: hippo:mirror
          jcr:primaryType: website:visualinternallink
          website:shortsummary: ''
        /website:tilesectionvisualhub[1]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Our free&nbsp;GCHQ-certified board-level training
              will help you to understand how cyber security risks could affect your
              organisation.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: GCHQ-certified board training
        /website:tilesectionvisualhub[2]:
          /website:tilesectionintroduction:
            hippostd:content: <p>We offer free onsite assessments to help your NHS
              organisation identify vulnerabilities and understand and overcome areas
              of high risk.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Onsite assessments
        /website:tilesectionvisualhub[3]:
          /website:tilesectionintroduction:
            hippostd:content: <p>To help your NHS organisation prepare for onsite
              cyber security reassessment, we offer free support to address cyber-critical
              issues that can have clinical impact and threaten patient safety.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Cyber operational readiness
        /website:tilesectionvisualhub[4]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Our free technical remediation service offers support
              to NHS Organisations to help fix technical issues in existing technology
              and systems to help achieve the Cyber Essential Plus accreditation.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical remediation
        jcr:primaryType: website:primarysectionvisualhub
        website:primarysectionheading: Incident management
      /website:primarysections[2]:
        /website:primarysectionlinks:
          /website:icon:
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
            jcr:primaryType: hippogallerypicker:imagelink
          /website:link:
            hippo:docbase: 4b6056e1-221a-4d3d-81dd-65a628e1efa1
            jcr:primaryType: hippo:mirror
          jcr:primaryType: website:visualinternallink
          website:shortsummary: ''
        /website:tilesectionvisualhub[1]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Technical Support Tile 1 introduction</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical Support Tile 1
        /website:tilesectionvisualhub[2]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Technical Support Tile 2 introduction</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical Support Tile 2
        jcr:primaryType: website:primarysectionvisualhub
        website:primarysectionheading: Technical Support
      /website:seosummary:
        hippostd:content: We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.
        jcr:primaryType: hippostd:html
      /website:summary:
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
        jcr:primaryType: hippostd:html
      common:searchRank: 3
      common:searchable: true
      hippo:availability:
      - preview
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2020-03-30T15:55:31.360Z
      hippostdpubwf:lastModificationDate: 2020-03-30T17:05:04.704Z
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 34470706-6ff2-458d-84e8-7c418f469f98
      hippotranslation:locale: en
      jcr:mixinTypes:
      - mix:referenceable
      - mix:versionable
      jcr:primaryType: website:visualhub
      website:shortsummary: Our information, data, and IT systems help health professionals,
        commissioners, analysts and managers give the best outcomes for patients.
      website:title: Services and resources
    /content[3]:
      /website:additionalinformation:
        hippostd:content: ''
        jcr:primaryType: hippostd:html
      /website:icon:
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
        jcr:primaryType: hippogallerypicker:imagelink
      /website:image:
        hippo:docbase: 4d3252da-3269-4acf-9641-2fae51b123dc
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
        jcr:primaryType: hippogallerypicker:imagelink
      /website:introduction:
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
        jcr:primaryType: hippostd:html
      /website:primarysections[1]:
        /website:primarysectionlinks:
          /website:icon:
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
            jcr:primaryType: hippogallerypicker:imagelink
          /website:link:
            hippo:docbase: dfcabd86-263b-4612-85b1-4d8c1be48530
            jcr:primaryType: hippo:mirror
          jcr:primaryType: website:visualinternallink
          website:shortsummary: ''
        /website:tilesectionvisualhub[1]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Our free&nbsp;GCHQ-certified board-level training
              will help you to understand how cyber security risks could affect your
              organisation.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: GCHQ-certified board training
        /website:tilesectionvisualhub[2]:
          /website:tilesectionintroduction:
            hippostd:content: <p>We offer free onsite assessments to help your NHS
              organisation identify vulnerabilities and understand and overcome areas
              of high risk.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Onsite assessments
        /website:tilesectionvisualhub[3]:
          /website:tilesectionintroduction:
            hippostd:content: <p>To help your NHS organisation prepare for onsite
              cyber security reassessment, we offer free support to address cyber-critical
              issues that can have clinical impact and threaten patient safety.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Cyber operational readiness
        /website:tilesectionvisualhub[4]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Our free technical remediation service offers support
              to NHS Organisations to help fix technical issues in existing technology
              and systems to help achieve the Cyber Essential Plus accreditation.</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical remediation
        jcr:primaryType: website:primarysectionvisualhub
        website:primarysectionheading: Incident management
      /website:primarysections[2]:
        /website:primarysectionlinks:
          /website:icon:
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
            jcr:primaryType: hippogallerypicker:imagelink
          /website:link:
            hippo:docbase: 4b6056e1-221a-4d3d-81dd-65a628e1efa1
            jcr:primaryType: hippo:mirror
          jcr:primaryType: website:visualinternallink
          website:shortsummary: ''
        /website:tilesectionvisualhub[1]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Technical Support Tile 1 introduction</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical Support Tile 1
        /website:tilesectionvisualhub[2]:
          /website:tilesectionintroduction:
            hippostd:content: <p>Technical Support Tile 2 introduction</p>
            jcr:primaryType: hippostd:html
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: Technical Support Tile 2
        jcr:primaryType: website:primarysectionvisualhub
        website:primarysectionheading: Technical Support
      /website:seosummary:
        hippostd:content: We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.
        jcr:primaryType: hippostd:html
      /website:summary:
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
        jcr:primaryType: hippostd:html
      common:searchRank: 3
      common:searchable: true
      hippo:availability:
      - live
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2020-03-30T15:55:31.360Z
      hippostdpubwf:lastModificationDate: 2020-03-30T17:05:04.704Z
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2020-03-30T17:05:10.715Z
      hippotranslation:id: 34470706-6ff2-458d-84e8-7c418f469f98
      hippotranslation:locale: en
      jcr:mixinTypes:
      - mix:referenceable
      jcr:primaryType: website:visualhub
      website:shortsummary: Our information, data, and IT systems help health professionals,
        commissioners, analysts and managers give the best outcomes for patients.
      website:title: Services and resources
    hippo:name: Services and resources
    hippo:versionHistory: 136fa638-e838-4501-8a90-ecc6b4695464
    jcr:mixinTypes:
    - hippo:named
    - hippo:versionInfo
    - mix:referenceable
    jcr:primaryType: hippo:handle
  hippo:name: Systems and services
  hippostd:foldertype:
  - new-digital-website-folder
  - new-digital-website-document
  hippotranslation:id: ca1ec125-235f-4465-958e-aca9978b8f84
  hippotranslation:locale: en
  jcr:mixinTypes:
  - hippo:named
  - hippotranslation:translated
  - mix:versionable
  jcr:primaryType: hippostd:folder
