/content/documents/corporate-website/services:
  .meta:order-before: data-and-information
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippo:named', 'hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 430b8f05-1dc0-424b-a3cb-62e58318ab2b
  hippo:name: Systems and services
  hippostd:foldertype: [new-digital-website-folder, new-digital-website-document]
  hippotranslation:id: ca1ec125-235f-4465-958e-aca9978b8f84
  hippotranslation:locale: en
  /content:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: 8a242cb2-5895-4a17-8b7e-8ad3d3c6513b
    hippo:name: Services and resources
    hippo:versionHistory: a781e867-f839-4ad6-a0cf-1dcf2159b31b
    /content[1]:
      jcr:primaryType: website:visualhub
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: bf67d21c-7168-4d2e-9f1f-19fa9923403f
      common:searchRank: 3
      common:searchable: true
      hippo:availability: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2020-04-01T14:37:02.068Z
      hippostdpubwf:lastModificationDate: 2020-04-01T14:37:02.068Z
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 74debfad-4072-43f0-a6ee-f71313d80f19
      hippotranslation:locale: en
      website:shortsummary: Our information, data, and IT systems help health professionals,
        commissioners, analysts and managers give the best outcomes for patients.
      website:title: Services and resources
      /website:additionalinformation:
        jcr:primaryType: hippostd:html
        hippostd:content: ''
      /website:icon:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /website:image:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4ca659c3-e8f0-4cc6-9233-fbf2eb3db67e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /website:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>&nbsp;</p>

          <p>We support health and care organisations to manage cyber security risk. This enables the safe and secure use of data and technology to deliver improved patient care.</p>
      /website:primarysections:
        jcr:primaryType: website:primarysectionvisualhub
        /website:tilesectionvisualhub:
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: ''
          /website:tilesectionintroduction:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /website:seosummary:
        jcr:primaryType: hippostd:html
        hippostd:content: We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.
      /website:summary:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
      /website:tilesectionvisualhub[1]:
        jcr:primaryType: website:tilesectionvisualhub
        website:tilesectionheading: Incident Management
        /website:tilesectionintroduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
        /website:tilesectionlinks[1]:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">GCHQ-certified board training</a>\r\
            \n\r\nOur free GCHQ-certified board-level training will help you to understand\
            \ how cyber security risks could affect your NHS organisation."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: b8fffcfc-fe57-4ec7-90df-3f9bcca43bbc
        /website:tilesectionlinks[2]:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">Onsite assessments</a>\r\n\r\nWe offer\
            \ free onsite assessments to help your NHS organisation identify vulnerabilities\
            \ and understand and overcome areas of high risk."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 1a21c2d6-f439-4a78-8d95-7e0e3866e5af
      /website:tilesectionvisualhub[2]:
        jcr:primaryType: website:tilesectionvisualhub
        website:tilesectionheading: Technical Support
        /website:tilesectionintroduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
        /website:tilesectionlinks:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">Cyber operational readiness support</a>\r\
            \n\r\nTo help your NHS organisation prepare for an onsite cyber security\
            \ reassessment, we offer free support to address security-critical issues\
            \ that can have clinical impact and threaten patient safety."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: dfcabd86-263b-4612-85b1-4d8c1be48530
    /content[2]:
      jcr:primaryType: website:visualhub
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: 95d48af9-39d5-4d3e-a841-36664909f296
      common:searchRank: 3
      common:searchable: true
      hippo:availability: [preview]
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2020-04-01T14:37:02.068Z
      hippostdpubwf:lastModificationDate: 2020-04-01T14:41:49.869Z
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 74debfad-4072-43f0-a6ee-f71313d80f19
      hippotranslation:locale: en
      website:shortsummary: Our information, data, and IT systems help health professionals,
        commissioners, analysts and managers give the best outcomes for patients.
      website:title: Services and resources
      /website:additionalinformation:
        jcr:primaryType: hippostd:html
        hippostd:content: ''
      /website:icon:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /website:image:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4ca659c3-e8f0-4cc6-9233-fbf2eb3db67e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /website:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>&nbsp;</p>

          <p>We support health and care organisations to manage cyber security risk. This enables the safe and secure use of data and technology to deliver improved patient care.</p>
      /website:primarysections:
        jcr:primaryType: website:primarysectionvisualhub
        /website:tilesectionvisualhub:
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: ''
          /website:tilesectionintroduction:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /website:seosummary:
        jcr:primaryType: hippostd:html
        hippostd:content: We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.
      /website:summary:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
      /website:tilesectionvisualhub[1]:
        jcr:primaryType: website:tilesectionvisualhub
        website:tilesectionheading: Incident Management
        /website:tilesectionintroduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
        /website:tilesectionlinks[1]:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">GCHQ-certified board training</a>\r\
            \n\r\nOur free GCHQ-certified board-level training will help you to understand\
            \ how cyber security risks could affect your NHS organisation."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: b8fffcfc-fe57-4ec7-90df-3f9bcca43bbc
        /website:tilesectionlinks[2]:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">Onsite assessments</a>\r\n\r\nWe offer\
            \ free onsite assessments to help your NHS organisation identify vulnerabilities\
            \ and understand and overcome areas of high risk."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 1a21c2d6-f439-4a78-8d95-7e0e3866e5af
      /website:tilesectionvisualhub[2]:
        jcr:primaryType: website:tilesectionvisualhub
        website:tilesectionheading: Technical Support
        /website:tilesectionintroduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
        /website:tilesectionlinks:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">Cyber operational readiness support</a>\r\
            \n\r\nTo help your NHS organisation prepare for an onsite cyber security\
            \ reassessment, we offer free support to address security-critical issues\
            \ that can have clinical impact and threaten patient safety."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: dfcabd86-263b-4612-85b1-4d8c1be48530
    /content[3]:
      jcr:primaryType: website:visualhub
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: 7cfef987-1bd4-4268-837e-4d989160f042
      common:searchRank: 3
      common:searchable: true
      hippo:availability: [live]
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2020-04-01T14:37:02.068Z
      hippostdpubwf:lastModificationDate: 2020-04-01T14:41:49.869Z
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2020-04-01T14:41:52.996Z
      hippotranslation:id: 74debfad-4072-43f0-a6ee-f71313d80f19
      hippotranslation:locale: en
      website:shortsummary: Our information, data, and IT systems help health professionals,
        commissioners, analysts and managers give the best outcomes for patients.
      website:title: Services and resources
      /website:additionalinformation:
        jcr:primaryType: hippostd:html
        hippostd:content: ''
      /website:icon:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /website:image:
        jcr:primaryType: hippogallerypicker:imagelink
        hippo:docbase: 4ca659c3-e8f0-4cc6-9233-fbf2eb3db67e
        hippo:facets: []
        hippo:modes: []
        hippo:values: []
      /website:introduction:
        jcr:primaryType: hippostd:html
        hippostd:content: |-
          <p>&nbsp;</p>

          <p>We support health and care organisations to manage cyber security risk. This enables the safe and secure use of data and technology to deliver improved patient care.</p>
      /website:primarysections:
        jcr:primaryType: website:primarysectionvisualhub
        /website:tilesectionvisualhub:
          jcr:primaryType: website:tilesectionvisualhub
          website:tilesectionheading: ''
          /website:tilesectionintroduction:
            jcr:primaryType: hippostd:html
            hippostd:content: ''
      /website:seosummary:
        jcr:primaryType: hippostd:html
        hippostd:content: We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.
      /website:summary:
        jcr:primaryType: hippostd:html
        hippostd:content: <p>We support health and care organisations to manage cyber
          security risk. This enables the safe and secure use of data and technology
          to deliver improved patient care.</p>
      /website:tilesectionvisualhub[1]:
        jcr:primaryType: website:tilesectionvisualhub
        website:tilesectionheading: Incident Management
        /website:tilesectionintroduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
        /website:tilesectionlinks[1]:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">GCHQ-certified board training</a>\r\
            \n\r\nOur free GCHQ-certified board-level training will help you to understand\
            \ how cyber security risks could affect your NHS organisation."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: b8fffcfc-fe57-4ec7-90df-3f9bcca43bbc
        /website:tilesectionlinks[2]:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">Onsite assessments</a>\r\n\r\nWe offer\
            \ free onsite assessments to help your NHS organisation identify vulnerabilities\
            \ and understand and overcome areas of high risk."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: 1a21c2d6-f439-4a78-8d95-7e0e3866e5af
      /website:tilesectionvisualhub[2]:
        jcr:primaryType: website:tilesectionvisualhub
        website:tilesectionheading: Technical Support
        /website:tilesectionintroduction:
          jcr:primaryType: hippostd:html
          hippostd:content: ''
        /website:tilesectionlinks:
          jcr:primaryType: website:visualinternallink
          website:shortsummary: "<a href=\"#\">Cyber operational readiness support</a>\r\
            \n\r\nTo help your NHS organisation prepare for an onsite cyber security\
            \ reassessment, we offer free support to address security-critical issues\
            \ that can have clinical impact and threaten patient safety."
          /website:icon:
            jcr:primaryType: hippogallerypicker:imagelink
            hippo:docbase: cafebabe-cafe-babe-cafe-babecafebabe
            hippo:facets: []
            hippo:modes: []
            hippo:values: []
          /website:link:
            jcr:primaryType: hippo:mirror
            hippo:docbase: dfcabd86-263b-4612-85b1-4d8c1be48530
